name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output environmental vars
        run: printenv
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"